### ISSUE TITLE
custom redirect is failing for me in 2.2

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/login_redirector#4]
i upgraded my site to 2.2 temporarily and am using login_redirector v5.0. the custom redirect that i setup is being ignored. my dev site (2.3) is working correctly.

**Comment by jdalsem** [comment]
Is the problem only with the custom redirect or also with normal redirects?

**Comment by propertunist** [comment]
i only tested with the custom redirect. i have now upgraded all servers to 2.3 - so am unable to go back and check. the custom redirect is working ok for me in 2.3

**Comment by jdalsem** [comment]
Closing this as we have no way of reproducing this
